/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import com.norris.fuzzy.core.cop.impl.BaseEntityTest;
	import com.norris.fuzzy.core.input.impl.InputManagerTest;
	import com.norris.fuzzy.core.resource.impl.BaseResourceTest;
	import com.norris.fuzzy.core.resource.impl.ResourceManagerTest;
	import com.norris.fuzzy.core.resource.impl.ResourceManagerTest1;
	import com.norris.fuzzy.core.sound.impl.SounderManagerTest;
	
	import flash.display.Sprite;
	import com.norris.fuzzy.core.cop.impl.EntityTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var com_norris_fuzzy_core_cop_impl_EntityTest_obj:com.norris.fuzzy.core.cop.impl.EntityTest;
		
		private var com_norris_fuzzy_core_sound_impl_SounderManagerTest_obj:com.norris.fuzzy.core.sound.impl.SounderManagerTest;
		private var com_norris_fuzzy_core_input_impl_InputManagerTest_obj:com.norris.fuzzy.core.input.impl.InputManagerTest;
		private var com_norris_fuzzy_core_cop_impl_BaseEntityTest_obj:com.norris.fuzzy.core.cop.impl.BaseEntityTest;
		private var com_norris_fuzzy_core_resource_impl_BaseResourceTest_obj:com.norris.fuzzy.core.resource.impl.BaseResourceTest;
		private var com_norris_fuzzy_core_resource_impl_ResourceManagerTest_obj:com.norris.fuzzy.core.resource.impl.ResourceManagerTest;
		private var com_norris_fuzzy_core_resource_impl_ResourceManagerTest1_obj:com.norris.fuzzy.core.resource.impl.ResourceManagerTest1;
	}
}